name: Bug Report
description: Create a report to help us improve.
labels: kind/bug,bug/need-confirmation
body:
  - type: markdown
    attributes:
      value: |
        # Welcome!

        The issue tracker is for reporting bugs. If you have an [idea for a new feature](https://github.com/grulicht/terraform-provider-wazuh/discussions/categories/ideas) or a [general question about Wazuh Terraform provider](https://github.com/grulicht/terraform-provider-wazuh/discussions/categories/help) please post in our [GitHub Discussions](https://github.com/grulicht/terraform-provider-wazuh/discussions).

        Please note that we only provide support for current versions of Wazuh.

        **DO NOT FILE ISSUES FOR GENERAL SUPPORT QUESTIONS**.

  - type: checkboxes
    id: terms
    attributes:
      label: Before you start please confirm the following.
      options:
        - label: Yes, I've searched similar issues on [GitHub](https://github.com/grulicht/terraform-provider-wazuh/issues).
          required: true
        - label: Yes, I've checked whether this issue is covered/solved in the Wazuh Terraform provider [discussions](https://github.com/grulicht/terraform-provider-wazuh/discussions/categories/help).
          required: true

  - type: markdown
    attributes:
      value: |
        # About your issue

        Tell us a bit about the issue you're having.

  - type: textarea
    attributes:
      label: Problem Description
      description: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Actual Behavior
      description: A clear and concise description of what actually happens.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: Please be as detailed as possible when providing steps to reproduce.
      placeholder: |
        1. Write a minimal Terraform config
        2. Run `terraform apply`
        3. Observe the error output
    validations:
      required: true

  - type: textarea
    attributes:
      label: Logs / Screenshots / Terraform Output
      description: Provide relevant logs or output from Terraform plan/apply, Wazuh logs, or any screenshots related to the issue.
    validations:
      required: true

  - type: input
    attributes:
      label: Affected Resource(s)
      description: |
        Name(s) of the resource(s) that are causing the issue. Example: wazuh_group etc.
    validations:
      required: true

  - type: input
    attributes:
      label: Terraform Command Used
      description: |
        The Terraform CLI command that triggered the issue. Example: terraform apply
    validations:
      required: true

  - type: textarea
    attributes:
      label: Relevant Terraform Configuration
      description: |
        Provide the Terraform configuration (HCL) that triggers the bug. You can redact sensitive values.
      render: hcl
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        # About your environment

        Tell us a bit about your Wazuh and Terraform environment.

  - type: input
    attributes:
      label: Provider Version
      description: |
        Version of the terraform-provider-wazuh. Example: v0.6.0
    validations:
      required: true

  - type: input
    attributes:
      label: Terraform/OpenTofu Version
      description: |
        Version of Terraform/OpenTofu. Example: 1.7.5
    validations:
      required: true

  - type: input
    attributes:
      label: Wazuh Version
      description: |
        Version of the Wazuh instance you are using. Example: 4.14.0
    validations:
      required: true

  - type: input
    attributes:
      label: Platform and Version
      description: |
        Enter your container management platform (Docker | Swarm | Kubernetes) along with the version. 
        Example: Docker 24.0.3 | Kubernetes 1.26
    validations:
      required: false

  - type: input
    attributes:
      label: OS and Architecture
      description: |
        Enter your Operating System, Version and Architecture. Example: Ubuntu 22.04, AMD64 | Raspbian OS, ARM64
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional Information
      description: |
        Any additional information about your environment, the bug, or anything else you think might be helpful.
    validations:
      required: false
